### ISSUE TITLE
host not found can't catch error

### ISSUE THREAD

**Issue by throrin19** [getprimate/primate#11]
Hi,
I've a big problem with Kong,

I recreate my Kong server and I launch Kongdash to change settings. The problem is, Kongdash have previous Kong url and settings and now, I get an empty window of the app.
Impossdible to change settings, connection, ...

It's possible to fix this problem really soon ?

Thanks

**Comment by linuxjuggler** [comment]
What is your OS ? and which version of KongDash you are using ?

**Comment by throrin19** [comment]
i'm on Linux with the version 0.2.0

**Comment by ajaysreedhar** [comment]
A new version (now called Primate) is released. Please open a new issue if this problem still exists.
