### ISSUE TITLE
kongdash start failed on centos7 

### ISSUE THREAD

**Issue by zhujinhu21** [getprimate/primate#12]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v7.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle KongDash@0.2.0~prestart: KongDash@0.2.0
6 silly lifecycle KongDash@0.2.0~prestart: no script for prestart, continuing
7 info lifecycle KongDash@0.2.0~start: KongDash@0.2.0
8 verbose lifecycle KongDash@0.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle KongDash@0.2.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/root/kongdash/node_modules/.bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/root/bin
10 verbose lifecycle KongDash@0.2.0~start: CWD: /root/kongdash
11 silly lifecycle KongDash@0.2.0~start: Args: [ '-c', 'gulp start' ]
12 silly lifecycle KongDash@0.2.0~start: Returned: code: 1  signal: null
13 info lifecycle KongDash@0.2.0~start: Failed to exec start script
14 verbose stack Error: KongDash@0.2.0 start: `gulp start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid KongDash@0.2.0
16 verbose cwd /root/kongdash
17 error Linux 3.10.0-327.el7.x86_64
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.2.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error KongDash@0.2.0 start: `gulp start`
22 error Exit status 1
23 error Failed at the KongDash@0.2.0 start script 'gulp start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the KongDash package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs KongDash
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls KongDash
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ajaysreedhar** [comment]
A new version (now called Primate) is released. Please open a new issue if this problem still exists.
