### ISSUE TITLE
No Plugins V0.10.2

### ISSUE THREAD

**Issue by inluxc** [getprimate/primate#15]
The Plugins are not showing in version 0.10.2
![screen shot 2017-05-09 at 09 27 17](https://cloud.githubusercontent.com/assets/584683/25841874/bcf9a74a-3499-11e7-9182-c07dacbc527c.png)

**Comment by nanaromance** [comment]
@inluxc  Plugin is applied on APIs object not on this page. Plugins page is showing all of the plugins only cannot add on this page.

**Comment by ajaysreedhar** [comment]
A new version (now called Primate) compatible with current latest Admin API is released.
Closing this issue.
