### ISSUE TITLE
Could not connect to Kong 0.11.0

### ISSUE THREAD

**Issue by janierj** [getprimate/primate#18]
I have Kong running locally, but when I try to connect using KongDash without username nor password, I see the follow error:

Error! Could not connect to http://localhost:8001.

While using Kong Dashboard (https://github.com/PGBI/kong-dashboard), it´s all fine.

Im using Kong 0.11.0

**Comment by nanaromance** [comment]
@janierj  Try this https://getkong.org/docs/0.10.x/secure-admin-api/#kong-api-loopback

**Comment by ajaysreedhar** [comment]
A new version (now called Primate) is released. Please open a new issue if the problem still exists.
