### ISSUE TITLE
Support for kong CE 0.13 release

### ISSUE THREAD

**Issue by jasonchester** [getprimate/primate#24]
The community edition of kong version 0.13 was recently released.

    konghq.com/blog/kong-ce-0-13-0-released
    Kong/kong@0.13.0 (release)

This release includes Services and Routes core entities as well as the deprecation of the API entity.

What are the plans / timeline for supporting the new version?

**Comment by jasonchester** [comment]
The community edition of kong version 0.13 was recently released.

    konghq.com/blog/kong-ce-0-13-0-released
    Kong/kong@0.13.0 (release)

This release includes Services and Routes core entities as well as the deprecation of the API entity.

What are the plans / timeline for supporting the new version?

**Comment by bmandrade** [comment]
Any news on this? It would be very welcome 😄

**Comment by niklasskeppstedt** [comment]
I am also looking for this, we are upgraded to Kong 0.13 and can no longer use kongdash...

**Comment by mjsprojects** [comment]
Kong at 0.14.0 now.

**Comment by singhraminder** [comment]
kong at 2.0 (alpha) now via https://bintray.com/kong/kong-preview

**Comment by ajaysreedhar** [comment]
A new version (now called Primate) compatible with current latest Admin API is released.
Closing this issue.
