### ISSUE TITLE
Error! could not load list of APIs.

### ISSUE THREAD

**Issue by SouthRibbleTech** [getprimate/primate#26]
When I open the APIs screen, I get the error

```
Error! could not load list of APIs.
```

When I try to create a new API. I get the error 

```
Error! Not found.
```

I assume I am connected to KONG, because the dashboard shows me some charts and I can create and save a consumer.

**Comment by ajaysreedhar** [comment]
which version of Kong do you have?

**Comment by ajaysreedhar** [comment]
> When I open the APIs screen, I get the error
> 
> ```
> Error! could not load list of APIs.
> ```
> 
> When I try to create a new API. I get the error
> 
> ```
> Error! Not found.
> ```
> 
> I assume I am connected to KONG, because the dashboard shows me some charts and I can create and save a consumer.

Which version of Kong do you have?

**Comment by sfoley** [comment]
Ive got the same issue running kong 1.2.1 and kongdash 0.3.0 on macos.

**Comment by jprando** [comment]
me too, same bug in version 0.3.0 on linux and windows too

**Comment by Throbing** [comment]
Done any thing I cound did,noting good luck,mybe think it's my fate~~~~

**Comment by ajaysreedhar** [comment]
@jprando @Throbing Could be a version compatibility issue. Next release is being cooked. Will be releasing soon.

**Comment by defcon8** [comment]
Same issue. Kong 1.4.0 <-> KongDash 0.3.0

**Comment by tovbinm** [comment]
Same issue. Are you planning on a new release @ajaysreedhar ?

**Comment by boob1991** [comment]
I have the same Issue 
Kong Version: 2.0.4

Kong Dash 0.3.0 @ajaysreedhar -> Please help

**Comment by ajaysreedhar** [comment]
Closing this issue. A new version (now called Primate) compatible with current latest Admin API is released.
