### ISSUE TITLE
Save preset settings

### ISSUE THREAD

**Issue by wshirey** [getprimate/primate#3]
As an admin with multiple kong instances (think kong instance per environment), I would like for Kong Dashboard to save Kong Settings for multiple instances to allow quicker navigation.

**Comment by wshirey** [comment]
Tabbed instances would be another way to implement.

**Comment by ajaysreedhar** [comment]
Thanks for the suggestion. Already working on it.!

**Comment by ajaysreedhar** [comment]
Latest version (renamed as Primate) saves settings for multiple instances.
