### ISSUE TITLE
There are two problems here

### ISSUE THREAD

**Issue by Goodku** [getprimate/primate#36]
Problem 1: Plugins were created incorrectly
![1](https://user-images.githubusercontent.com/109283965/178967851-18d25265-c915-4572-95dc-d507d681fa63.png)
Cause: The timestamp is not performed on the create_at of the plugins
![2](https://user-images.githubusercontent.com/109283965/178968106-b6366fee-211c-4c33-9093-c407d4db72b9.png)
Issue 2: Service creation is not supported in kong 2.6 and previous versions
![3](https://user-images.githubusercontent.com/109283965/178968482-4520a790-4be7-40eb-89e9-efa93b881131.png)
Reason: 2.6 and previous versions of kong do not have an enabled field at the service
![4](https://user-images.githubusercontent.com/109283965/178968711-c04146a8-148b-43cf-8172-5cd33dd10ebd.png)
![5](https://user-images.githubusercontent.com/109283965/178970470-948756e8-b5b7-4be5-9ddf-a894c9bac8e7.png)
![6](https://user-images.githubusercontent.com/109283965/178970500-4d00fe4f-cde4-4fd6-be3a-465aadcdfac9.png)
If you can, I hope this management tool can support kong2.6 and below, thank you
I am a beginner and my English is not very good

**Comment by ajaysreedhar** [comment]
@Goodku Thanks for reporting.
