### ISSUE TITLE
username and password don't work when admin api is proxied via kong and protected by basic-auth plugin

### ISSUE THREAD

**Issue by capardemus** [getprimate/primate#40]
Hi,
username and password don't work when admin api is proxied via kong and protected by basic-auth plugin.
Example: admin api url : 192.168.1.126:8000/admin-api
Message returned: user is unauthorized.
Have an idea?

**Comment by ajaysreedhar** [comment]
Hi @capardemus Thanks for reporting. Will check...

**Comment by talyssonlima** [comment]
also with the same problem

**Comment by nignacio-struqtive** [comment]
Has anybody been able to find a workaround for this?

**Comment by capardemus** [comment]
Hi nignacio,
The only workaround, i 've found, was to install the last version of Kong
community to use the kong manager and secure it from the embedded nginx.
Hope it will help you. Primate is no longer useable.

Regards;

**Comment by nignacio-struqtive** [comment]
@capardemus Thanks for your reply. 
I ended up deep-diving into the code and modified (read hack) the bits I needed to get it working.

**Comment by raoxiaoyan** [comment]
The same issue with the kong latest version 3.4

**Comment by ajaysreedhar** [comment]
This issue is fixed in the new update. Please check [v1.1.0](https://github.com/getprimate/primate/releases/tag/v1.1.0)
