### ISSUE TITLE
How to connect to admin-api hidden behind kong proxy?

### ISSUE THREAD

**Issue by wojciechignasiak** [getprimate/primate#43]
Hi,
Is there a way to connect to admin-api hidden behind kong proxy?
I filled out the form as in the ss below, but it is not working.
<img width="937" alt="Zrzut ekranu 2023-01-18 o 18 53 24" src="https://user-images.githubusercontent.com/84650124/213257500-f28babe8-00e6-41cf-9da8-28293fd39dbc.png">

I tried to modify code just for test in file client-setup.js in line 118:
```const url = `${setupModel.protocol}://${setupModel.adminHost}:${setupModel.adminPort}/admin-api`;```
Then I tried to build it following instructions from readme section. Unfortunately I wasn't able to start or generate app:
<img width="1355" alt="Zrzut ekranu 2023-01-18 o 18 49 40" src="https://user-images.githubusercontent.com/84650124/213257173-1e1c807c-6cff-48d4-ab64-bd5f03124e47.png">

**Comment by ajaysreedhar** [comment]
Hi Wojciech, 
The above error occurred because the preload.js script was not compatible with process sandboxing (Starting from Electron 20, the sandbox is enabled by default).
I have updated the pre-load files. 
Please pull the main branch and try again.

**Comment by ajaysreedhar** [comment]
Cool. Closing the issue.
