### ISSUE TITLE
Is it possible to have a customizable connection options

### ISSUE THREAD

**Issue by jirawatsena1995** [getprimate/primate#45]
Normally we have like http://localhost:8001 as a connection.
I wonder if we can have a customization option like http://localhost:8000/admin-api in case we proxy kong admin api behind itself as per this [article ](https://docs.konghq.com/gateway/latest/production/running-kong/secure-admin-api/#kong-api-loopback)

**Comment by talyssonlima** [comment]
Any solution for this?

**Comment by dambros-nstech** [comment]
Same doubt for me. Couldn't find the solution so far

**Comment by ajaysreedhar** [comment]
Yes. Please check the new update https://github.com/getprimate/primate/releases/tag/v1.1.0
