### ISSUE TITLE
Plugins are not displayed well.

### ISSUE THREAD

**Issue by se** [getprimate/primate#7]
Plugins are not displayed well when I'm trying to add a plugin to API. 

![image](https://cloud.githubusercontent.com/assets/491844/19020277/271dc028-88ad-11e6-8f01-bb8457e87087.png)

**Comment by linuxjuggler** [comment]
Which version you are using ? cause I cant seems to face the problem on my side

![screen shot 2016-10-03 at 10 26 57 am](https://cloud.githubusercontent.com/assets/27624/19030061/015cc8e6-8954-11e6-8a4e-ae54b54c78be.png)

**Comment by se** [comment]
My version is 0.9.0.

**Comment by linuxjuggler** [comment]
have you tried to upgrade the Kong to version 0.9.2 .
and which version of the dashboard you are using ?

am using version 0.2.0 from KongDash and 0.9.2 from Kong

**Comment by linuxjuggler** [comment]
Kong "Revert the /plugins/enabled endpoint's response to be a JSON array, and not an Object" https://github.com/Mashape/kong/pull/1529

**Comment by se** [comment]
I didn't tried. I am using latest version (master branch) of it.

**Comment by linuxjuggler** [comment]
try to upgrade Kong and let us know the result so that we can put a note on the readme file

**Comment by se** [comment]
Yes it worked when I upgrade it to 0.9.2 but, my fix is working with 0.9.x not just with 0.9.2 ;) Maybe you can check it.

https://github.com/ajaysreedhar/kongdash/pull/8/commits/57babb8b1e476ca02fe9cb31ec5beab43ae674ce

**Comment by linuxjuggler** [comment]
@se sounds interesting but usually those fixes goes into `develop` branch not directly into `master` branch ..

any way am sure the maintainer will look into it soon.

**Comment by ajaysreedhar** [comment]
A new version (now called Primate) compatible with current latest Admin API is released.
Closing this issue.
